name: Ruby Gem Release

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            ruby: 'jruby'
            jacorb_version: '3.1'
            java-version: '8'
            java-package: 'jdk'
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.ruby }}-jacorb-${{ matrix.jacorb_version }}-${{ matrix.java-package }}-${{ matrix.java-version }}
    env:
      JACORB_HOME: ${{ github.workspace }}/jacorb/jacorb-${{ matrix.jacorb_version }}
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
        java-package: ${{ matrix.java-package }}
        architecture: 'x64'
    - name: checkout r2corba
      uses: actions/checkout@v2
    - name: Download a file
      uses: carlosperate/download-file-action@v1.0.3
      id: download-jacorb
      with:
        file-url: 'https://www.jacorb.org/releases/${{ matrix.jacorb_version }}/jacorb-${{ matrix.jacorb_version }}-binary.zip'
        file-name: 'jacorb-${{ matrix.jacorb_version }}.zip'
        location: '${{ github.workspace }}'
    - uses: montudor/action-zip@v0.1.1
      with:
        args: unzip -qq jacorb-${{ matrix.jacorb_version }}.zip -d jacorb
    - name: Run rake gem
      run: |
        rake gem
        ls -al pkg
      shell: pwsh
